"""add festivals

Revision ID: e8f71c078869
Revises: ffc8f9228ed4
Create Date: 2024-06-09 03:17:10.283857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f71c078869'
down_revision: Union[str, None] = 'ffc8f9228ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('festival_content', sa.String(length=300), nullable=True),
    sa.Column('festival_photo', sa.String(length=2048), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('festival_id')
    )
    op.add_column('accommodation_info', sa.Column('latitude', sa.String(length=100), nullable=True))
    op.add_column('accommodation_info', sa.Column('longitude', sa.String(length=100), nullable=True))
    op.add_column('plan_component', sa.Column('festival_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan_component', 'festivals', ['festival_id'], ['festival_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_component', type_='foreignkey')
    op.drop_column('plan_component', 'festival_id')
    op.drop_column('accommodation_info', 'longitude')
    op.drop_column('accommodation_info', 'latitude')
    op.drop_table('festivals')
    # ### end Alembic commands ###
